print("🚀 Welcome to Project Polaris!")
print("Commander: Geetha")
print("Mission Control: Ponyo")
print("Small steps. Clear direction. Infinite sky.")
print("mission 006 in progress")
print("mission 006 completed!")