print("🚀 Welcome to Project Polaris!")
print("Commander: Geetha")
print("Mission Control: Ponyo")
print("Small steps. Clear direction. Infinite sky.")
print("mission 006 in progress")
print("mission 006 completed!")
print("mission 007 started!")
print("undo the staging area")
print("Mission 009 in progress")
